// <auto-generated />
namespace CRAMWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedbuildingsleveltostate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedbuildingsleveltostate));
        
        string IMigrationMetadata.Id
        {
            get { return "201806170629011_Added buildings level to state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
